/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.OvertimeController;
import controllers.OvertimeControllerInterface;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Overtime;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.view.JasperViewer;
import org.hibernate.SessionFactory;
import org.hibernate.engine.jdbc.connections.spi.ConnectionProvider;
import tools.HibernateUtil;

/**
 *
 * @author AdhityaWP
 */
public class ManagerMainView extends javax.swing.JInternalFrame {

    SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
    DefaultTableModel myTableModel = new DefaultTableModel();
    OvertimeControllerInterface oci = new OvertimeController(sessionFactory);

    JasperReport JasRep;
    JasperPrint JasPri;
    Map param = new HashMap();
    JasperDesign JasDes;
    Connection c;

    /**
     * Creates new form ManagerView
     */
    public ManagerMainView() {
        initComponents();
        tableData(oci.getAll());
    }

    private void tableData(List<Overtime> overtime) {
        Object[] columnNames = {"No", "ID Overtime", "Employee Name", "Overtime Date", "Duration(hours)", "Keterangan", "TimeSheet", "Status"};
        Object[][] data = new Object[overtime.size()][columnNames.length];
        for (int i = 0; i < data.length; i++) {
            data[i][0] = (i + 1);
            data[i][1] = overtime.get(i).getId();
            data[i][2] = overtime.get(i).getTimeSheet().getEmployee().getName();
            data[i][3] = overtime.get(i).getOvertimeDate();
            data[i][4] = overtime.get(i).getTimeDuration();
            data[i][5] = overtime.get(i).getKeterangan();
            data[i][6] = overtime.get(i).getTimeSheet().getId();
            data[i][7] = overtime.get(i).getStatus();
        }
        myTableModel = new DefaultTableModel(data, columnNames);
        tbManager.setModel(myTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnManagerMain = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSubTitle = new javax.swing.JLabel();
        spMain = new javax.swing.JSeparator();
        pnUser = new javax.swing.JPanel();
        lblNik = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        spTableManager = new javax.swing.JScrollPane();
        tbManager = new javax.swing.JTable();
        lblSearch = new javax.swing.JLabel();
        tfSearch = new javax.swing.JTextField();
        chbSearch = new javax.swing.JCheckBox();
        btSearch = new javax.swing.JButton();
        btApprove = new javax.swing.JButton();
        tfId = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tfDate = new javax.swing.JTextField();
        tfCount = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblCount = new javax.swing.JLabel();
        btPrint = new javax.swing.JButton();
        lblTimeSheet = new javax.swing.JLabel();
        tfImeSheet = new javax.swing.JTextField();
        tfStatus = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfKeterangan = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        miManager = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setClosable(true);
        setTitle("Manager Main");

        pnManagerMain.setBackground(new java.awt.Color(199, 220, 236));

        lblTitle.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        lblTitle.setText("OVERTIME REQUEST");

        lblSubTitle.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        lblSubTitle.setText("Mitra Integrasi Informatika");

        pnUser.setBackground(new java.awt.Color(199, 200, 239));

        lblNik.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        lblNik.setText("NIK");

        lblUsername.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblUsername.setText("Username");

        javax.swing.GroupLayout pnUserLayout = new javax.swing.GroupLayout(pnUser);
        pnUser.setLayout(pnUserLayout);
        pnUserLayout.setHorizontalGroup(
            pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addGap(87, 87, 87))
        );
        pnUserLayout.setVerticalGroup(
            pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnUserLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNik, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbManager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbManagerMouseClicked(evt);
            }
        });
        spTableManager.setViewportView(tbManager);

        lblSearch.setText("Search");

        chbSearch.setText("By Id");

        btSearch.setText("Search!");
        btSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSearchActionPerformed(evt);
            }
        });

        btApprove.setText("Approve");
        btApprove.setEnabled(false);
        btApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btApproveActionPerformed(evt);
            }
        });

        lblId.setText("Id OT");

        lblName.setText("Name");

        lblDate.setText("Date");

        lblCount.setText("Duration");

        btPrint.setText("Print Report");
        btPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrintActionPerformed(evt);
            }
        });

        lblTimeSheet.setText("TimeSheet");

        jLabel1.setText("Status");

        jLabel2.setText("Keterangan");

        javax.swing.GroupLayout pnManagerMainLayout = new javax.swing.GroupLayout(pnManagerMain);
        pnManagerMain.setLayout(pnManagerMainLayout);
        pnManagerMainLayout.setHorizontalGroup(
            pnManagerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnManagerMainLayout.createSequentialGroup()
                .addGroup(pnManagerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spMain)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnManagerMainLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnManagerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnManagerMainLayout.createSequentialGroup()
                                .addGroup(pnManagerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDate)
                                    .addComponent(lblCount)
                                    .addComponent(lblName)
                                    .addComponent(lblId))
                                .addGap(32, 32, 32)
                                .addGroup(pnManagerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfDate, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                    .addComponent(tfName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfId, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfCount))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnManagerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnManagerMainLayout.createSequentialGroup()
                                        .addGroup(pnManagerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTimeSheet)
                                            .addComponent(jLabel1))
                                        .addGap(6, 6, 6))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnManagerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnManagerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfStatus, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfImeSheet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btApprove))
                                .addGap(30, 30, 30)
                                .addComponent(pnUser, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnManagerMainLayout.createSequentialGroup()
                                .addComponent(btPrint)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnManagerMainLayout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(38, 38, 38)
                .addComponent(lblSubTitle)
                .addGap(94, 94, 94))
            .addGroup(pnManagerMainLayout.createSequentialGroup()
                .addGroup(pnManagerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spTableManager)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnManagerMainLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnManagerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSearch)
                            .addGroup(pnManagerMainLayout.createSequentialGroup()
                                .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chbSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btSearch)))))
                .addContainerGap())
        );
        pnManagerMainLayout.setVerticalGroup(
            pnManagerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnManagerMainLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnManagerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSubTitle)
                    .addComponent(lblTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spMain, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnManagerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnManagerMainLayout.createSequentialGroup()
                        .addGroup(pnManagerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnManagerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnManagerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnManagerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCount)))
                    .addComponent(pnUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnManagerMainLayout.createSequentialGroup()
                        .addGroup(pnManagerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTimeSheet)
                            .addComponent(tfImeSheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnManagerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnManagerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(btApprove)))
                .addGap(35, 35, 35)
                .addComponent(lblSearch)
                .addGap(7, 7, 7)
                .addGroup(pnManagerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbSearch)
                    .addComponent(btSearch)
                    .addComponent(btPrint))
                .addGap(18, 18, 18)
                .addComponent(spTableManager, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        miManager.setText("MENU");

        jMenuItem1.setText("jMenuItem1");
        miManager.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        miManager.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem3");
        miManager.add(jMenuItem3);

        jMenuItem4.setText("jMenuItem4");
        miManager.add(jMenuItem4);

        jMenuItem5.setText("jMenuItem5");
        miManager.add(jMenuItem5);

        jMenuBar1.add(miManager);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnManagerMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnManagerMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSearchActionPerformed
        String key = tfSearch.getText().toString();
        boolean cb = chbSearch.isSelected();
        if (!cb) {
            tableData(oci.getData(key));
        } else {
//            Region tampungan = rc.getById(key);
//            tfId.setText(tampungan.getId() + "");
//            tfNama.setText(tampungan.getName());
//            Object[] data = {1, tampungan.getId(), tampungan.getName()};
//            Object[] columnNames = {"No", "Id", "Nama"};
//            model = new DefaultTableModel(null, columnNames);
//            tbRegion.setModel(model);
//            model.addRow(data);
        }
    }//GEN-LAST:event_btSearchActionPerformed

    private void tbManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbManagerMouseClicked
        tfId.setText(tbManager.getValueAt(tbManager.getSelectedRow(), 1).toString());
        tfName.setText(tbManager.getValueAt(tbManager.getSelectedRow(), 2).toString());
        tfDate.setText(tbManager.getValueAt(tbManager.getSelectedRow(), 3).toString());
        tfCount.setText(tbManager.getValueAt(tbManager.getSelectedRow(), 4).toString());
        tfKeterangan.setText(tbManager.getValueAt(tbManager.getSelectedRow(), 5).toString());
        tfImeSheet.setText(tbManager.getValueAt(tbManager.getSelectedRow(), 6).toString());
        tfStatus.setText(tbManager.getValueAt(tbManager.getSelectedRow(), 7).toString());

        tfId.setEnabled(false);
        btApprove.setEnabled(true);
    }//GEN-LAST:event_tbManagerMouseClicked

    private void btApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btApproveActionPerformed
        int reply = JOptionPane.showConfirmDialog(null, "Are You Sure Want to Approve this Overtime?", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (reply == JOptionPane.YES_OPTION) {
            String id = tfId.getText();
            String date = tfDate.getText();
            String duration = tfCount.getText();
            String keterangan = tfKeterangan.getText();
            String timesheet = tfImeSheet.getText();
            String status = tfStatus.getText();
            if (status.equals("0")) {
                oci.update(id, date, duration, keterangan, "1", timesheet);
                JOptionPane.showMessageDialog(null, "Success for approve!");
            } else {
                JOptionPane.showMessageDialog(null, "Request has been approve!");
            }
            tableData(oci.getAll());

        }
    }//GEN-LAST:event_btApproveActionPerformed

    private void btPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrintActionPerformed
        try {
            c = sessionFactory.
                    getSessionFactoryOptions().getServiceRegistry().
                    getService(ConnectionProvider.class).getConnection();
        } catch (SQLException ex) {
            Logger.getLogger(ManagerMainView.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            String fileName = "./src/reports/report1.jrxml";
            String filetoFill = "./src/reports/report1.jasper";
            JasperCompileManager.compileReport(fileName);
            JasPri = JasperFillManager.fillReport(filetoFill, param, c);
            JasperViewer.viewReport(JasPri, false);

        } catch (JRException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btPrintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btApprove;
    private javax.swing.JButton btPrint;
    private javax.swing.JButton btSearch;
    private javax.swing.JCheckBox chbSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNik;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblSubTitle;
    private javax.swing.JLabel lblTimeSheet;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JMenu miManager;
    private javax.swing.JPanel pnManagerMain;
    private javax.swing.JPanel pnUser;
    private javax.swing.JSeparator spMain;
    private javax.swing.JScrollPane spTableManager;
    private javax.swing.JTable tbManager;
    private javax.swing.JTextField tfCount;
    private javax.swing.JTextField tfDate;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfImeSheet;
    private javax.swing.JTextField tfKeterangan;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfSearch;
    private javax.swing.JTextField tfStatus;
    // End of variables declaration//GEN-END:variables
}
