/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newviews;

import controllers.EmployeeController;
import controllers.EmployeeControllerInterface;
import controllers.UserController;
import controllers.UserControllerInterface;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Employee;
import models.Sessions;
import org.hibernate.SessionFactory;
import tools.HibernateUtil;
import views.AdminView;
import views.EmployeeMainView;
import views.ManagerMainView;

/**
 *
 * @author milhamafemi
 */
public class MainView extends javax.swing.JFrame {

    SessionFactory factory = HibernateUtil.getSessionFactory();
    DefaultTableModel myTable = new DefaultTableModel();
    UserControllerInterface uc = new UserController(factory);
    EmployeeControllerInterface ec = new EmployeeController(factory);
    /**
     * Creates new form LoginOrRegisterView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        pnLoginOrRegister = new javax.swing.JPanel();
        lblOr = new javax.swing.JLabel();
        btRegister = new javax.swing.JButton();
        btLogin1 = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        pnLogin = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        lblPassword = new javax.swing.JLabel();
        btLogin = new javax.swing.JButton();
        btCancel = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        pnGimmick = new javax.swing.JPanel();
        MII = new javax.swing.JLabel();
        pnActivation = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        tfNIK = new javax.swing.JTextField();
        lblUsername2 = new javax.swing.JLabel();
        btActiveAccount = new javax.swing.JButton();
        btCancelActAcc = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(null);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        MainPanel.setLayout(new javax.swing.OverlayLayout(MainPanel));
        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnLoginOrRegister.setBackground(new java.awt.Color(51, 153, 255));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("newviews/Bundle"); // NOI18N
        lblOr.setText(bundle.getString("MainView.lblOr.text")); // NOI18N

        btRegister.setBackground(new java.awt.Color(128, 137, 149));
        btRegister.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        btRegister.setText(bundle.getString("MainView.btRegister.text")); // NOI18N
        btRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegisterActionPerformed(evt);
            }
        });

        btLogin1.setBackground(new java.awt.Color(128, 137, 149));
        btLogin1.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        btLogin1.setText(bundle.getString("MainView.btLogin1.text")); // NOI18N
        btLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogin1ActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 255));
        lblTitle.setText(bundle.getString("MainView.lblTitle.text")); // NOI18N

        javax.swing.GroupLayout pnLoginOrRegisterLayout = new javax.swing.GroupLayout(pnLoginOrRegister);
        pnLoginOrRegister.setLayout(pnLoginOrRegisterLayout);
        pnLoginOrRegisterLayout.setHorizontalGroup(
            pnLoginOrRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLoginOrRegisterLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(pnLoginOrRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLoginOrRegisterLayout.createSequentialGroup()
                        .addComponent(btLogin1)
                        .addGap(19, 19, 19)
                        .addComponent(lblOr)
                        .addGap(18, 18, 18)
                        .addComponent(btRegister)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLoginOrRegisterLayout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        pnLoginOrRegisterLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btLogin1, btRegister});

        pnLoginOrRegisterLayout.setVerticalGroup(
            pnLoginOrRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLoginOrRegisterLayout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(81, 81, 81)
                .addGroup(pnLoginOrRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLogin1)
                    .addComponent(lblOr)
                    .addComponent(btRegister))
                .addGap(47, 47, 47))
        );

        getContentPane().add(pnLoginOrRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 440, 310));

        pnLogin.setBackground(new java.awt.Color(204, 204, 204));

        lblUsername.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        lblUsername.setText(bundle.getString("MainView.lblUsername.text")); // NOI18N

        tfUsername.setForeground(new java.awt.Color(51, 255, 255));

        tfPassword.setForeground(new java.awt.Color(51, 255, 255));

        lblPassword.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        lblPassword.setText(bundle.getString("MainView.lblPassword.text")); // NOI18N

        btLogin.setBackground(new java.awt.Color(128, 137, 149));
        btLogin.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        btLogin.setText(bundle.getString("MainView.btLogin.text")); // NOI18N
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });

        btCancel.setBackground(new java.awt.Color(128, 137, 149));
        btCancel.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        btCancel.setText(bundle.getString("MainView.btCancel.text")); // NOI18N
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout pnLoginLayout = new javax.swing.GroupLayout(pnLogin);
        pnLogin.setLayout(pnLoginLayout);
        pnLoginLayout.setHorizontalGroup(
            pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLoginLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername)
                    .addComponent(lblPassword))
                .addGap(55, 55, 55)
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfUsername)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnLoginLayout.createSequentialGroup()
                        .addComponent(btLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnLoginLayout.setVerticalGroup(
            pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLoginLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106)
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassword)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLogin)
                    .addComponent(btCancel))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pnLoginLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btCancel, btLogin});

        getContentPane().add(pnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 440, 310));

        MII.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/MII.png"))); // NOI18N
        MII.setText(bundle.getString("MainView.MII.text")); // NOI18N

        javax.swing.GroupLayout pnGimmickLayout = new javax.swing.GroupLayout(pnGimmick);
        pnGimmick.setLayout(pnGimmickLayout);
        pnGimmickLayout.setHorizontalGroup(
            pnGimmickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGimmickLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MII, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
        );
        pnGimmickLayout.setVerticalGroup(
            pnGimmickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGimmickLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(MII)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        getContentPane().add(pnGimmick, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 620));

        pnActivation.setBackground(new java.awt.Color(204, 204, 204));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 255));

        lblUsername2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        lblUsername2.setText(bundle.getString("MainView.lblUsername2.text")); // NOI18N

        btActiveAccount.setBackground(new java.awt.Color(128, 137, 149));
        btActiveAccount.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        btActiveAccount.setText(bundle.getString("MainView.btActiveAccount.text")); // NOI18N
        btActiveAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActiveAccountActionPerformed(evt);
            }
        });

        btCancelActAcc.setBackground(new java.awt.Color(128, 137, 149));
        btCancelActAcc.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        btCancelActAcc.setText(bundle.getString("MainView.btCancelActAcc.text")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel5.setText(bundle.getString("MainView.jLabel5.text")); // NOI18N

        javax.swing.GroupLayout pnActivationLayout = new javax.swing.GroupLayout(pnActivation);
        pnActivation.setLayout(pnActivationLayout);
        pnActivationLayout.setHorizontalGroup(
            pnActivationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnActivationLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblUsername2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnActivationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnActivationLayout.createSequentialGroup()
                        .addComponent(btActiveAccount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelActAcc))
                    .addComponent(tfNIK))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnActivationLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        pnActivationLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btActiveAccount, btCancelActAcc});

        pnActivationLayout.setVerticalGroup(
            pnActivationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnActivationLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(pnActivationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnActivationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btActiveAccount)
                    .addComponent(btCancelActAcc))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pnActivationLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btActiveAccount, btCancelActAcc});

        getContentPane().add(pnActivation, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 440, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        // TODO add your handling code here:
        String pass = "";
        for (char c : tfPassword.getPassword()) {
            pass += c;
        }
        if ((uc.login(tfUsername.getText(), pass))) {
            JOptionPane.showMessageDialog(null, "Login Sukses.");
            this.setVisible(false);
            String u = ec.getById(Sessions.getId()).getRoleList().get(0).getJob().getId();
            if (u.equals("J01")) {
                ManagerMainView mv = new ManagerMainView();
                this.getParent().add(mv);
                mv.setVisible(true);
            } else if (u.equals("J02")) {
                EmployeeMainView ev = new EmployeeMainView();
                this.getParent().add(ev);
                ev.setVisible(true);
            } else {
                AdminView av = new AdminView();
                this.getParent().add(av);
                av.setVisible(true);
            }
            //            Employee u = ec.getById(Sessions.getId());
        } else {
            tfUsername.setText("");
            tfPassword.setText("");
            JOptionPane.showMessageDialog(null, "Username atau Password salah.");
        }
    }//GEN-LAST:event_btLoginActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        // TODO add your handling code here:
        tfUsername.setText("");
        tfPassword.setText("");

    }//GEN-LAST:event_btCancelActionPerformed

    private void btRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegisterActionPerformed
        
        pnActivation.setVisible(true);
        pnLogin.setVisible(false);

    }//GEN-LAST:event_btRegisterActionPerformed

    private void btLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogin1ActionPerformed
        //        ManagerMainView mmv = new ManagerMainView();
        pnActivation.setVisible(false);
        pnLogin.setVisible(true);
    }//GEN-LAST:event_btLogin1ActionPerformed

    private void btActiveAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActiveAccountActionPerformed
        // TODO add your handling code here:
        String z = tfNIK.getText();
        Employee a = ec.getById(z);
        if(uc.save(a.getId(), a.getEmail()+a.getId(), a.getId())){
            JOptionPane.showMessageDialog(null, "Aktivasi Berhasil");
        }
        else{
            JOptionPane.showMessageDialog(null, "Aktivasi Gagal");
        }
    }//GEN-LAST:event_btActiveAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MII;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton btActiveAccount;
    private javax.swing.JButton btCancel;
    private javax.swing.JButton btCancelActAcc;
    private javax.swing.JButton btLogin;
    private javax.swing.JButton btLogin1;
    private javax.swing.JButton btRegister;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblOr;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblUsername2;
    private javax.swing.JPanel pnActivation;
    private javax.swing.JPanel pnGimmick;
    private javax.swing.JPanel pnLogin;
    private javax.swing.JPanel pnLoginOrRegister;
    private javax.swing.JTextField tfNIK;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
