/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newviews;

import controllers.EmployeeController;
import controllers.EmployeeControllerInterface;
import controllers.OvertimeController;
import controllers.OvertimeControllerInterface;
import controllers.TimeSheetController;
import controllers.TimeSheetControllerInterface;
import java.awt.Color;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import models.Employee;
import models.Overtime;
import models.Sessions;
import models.TimeSheet;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.view.JasperViewer;
import org.hibernate.SessionFactory;
import org.hibernate.engine.jdbc.connections.spi.ConnectionProvider;
import tools.HibernateUtil;
import views.ManagerMainView;
import views.OvertimeReportView;

/**
 *
 * @author milhamafemi
 */
public class UserView extends javax.swing.JInternalFrame {

    DefaultTableModel myTableModel = new DefaultTableModel();
    SessionFactory factory = HibernateUtil.getSessionFactory();
    DefaultTableModel myTable = new DefaultTableModel();
    OvertimeControllerInterface oc = new OvertimeController(factory);
    String id = Sessions.getId();
    TimeSheetControllerInterface tc = new TimeSheetController(factory);
    EmployeeControllerInterface ec = new EmployeeController(factory);
    JasperReport JasRep;
    JasperPrint JasPri;
    Map param = new HashMap();
    JasperDesign JasDes;
    Connection c;

    /**
     * Creates new form UserView
     */
    public UserView() {
        initComponents();
//        List a = ec.getById(id).getTimeSheetList();
//        Employee u = ec.getById(id);
//        lblNik.setText(u.getId());
//        lblUsername.setText(u.getName());
//        tableData(a);
    }

    private void setukuran() {
        this.setSize(670, 510);
    }

    private void tableData(List<TimeSheet> ts) {
//        jobs = jc.getAll();
        Object[] columnNames = {"Nomor", "Id", "Overtime Date", "Duration", "Status"};

        Object[][] data = new Object[ts.size()][columnNames.length];

        for (int i = 0; i < data.length; i++) {
            data[i][0] = (i + 1);
            data[i][1] = ts.get(i).getId();
            for (Object obj : tc.getByid(ts.get(i).getId()).getOvertimeList()) {
                Overtime overtime = (Overtime) obj;
                data[i][2] = overtime.getOvertimeDate();
                data[i][3] = overtime.getTimeDuration();
                data[i][4] = overtime.getStatus();
//      

            }
        }
        myTable = new DefaultTableModel(data, columnNames);
        tbEmployee.setModel(myTable);
    }

    private void setColor(JPanel pane) {
        pane.setBackground(new Color(41, 57, 80));
    }

    private void resetColor(JPanel[] pane, JPanel[] indicators) {
        for (int i = 0; i < pane.length; i++) {
            pane[i].setBackground(new Color(23, 35, 51));

        }
        for (int i = 0; i < indicators.length; i++) {
            indicators[i].setOpaque(false);
        }

    }

    private void getRidTheBar() {
        putClientProperty("Home.isPallete", Boolean.TRUE);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        ((BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.setBorder(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dynamicPane = new javax.swing.JLayeredPane();
        pnHistory = new javax.swing.JPanel();
        spTableManager = new javax.swing.JScrollPane();
        tbEmployee = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        pnUserSession = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblNik = new javax.swing.JLabel();
        pnEmpReport = new javax.swing.JPanel();
        pnReportEmpOt = new javax.swing.JPanel();
        btReport = new javax.swing.JButton();
        pnOvtReport = new javax.swing.JPanel();
        btOtReport = new javax.swing.JButton();
        pnMenu = new javax.swing.JPanel();
        btnHome = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHistory = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAbout = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnHias1 = new javax.swing.JPanel();
        pnHias2 = new javax.swing.JPanel();
        pnHias3 = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(930, 620));
        setPreferredSize(new java.awt.Dimension(930, 620));

        dynamicPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnHistory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEmployeeMouseClicked(evt);
            }
        });
        spTableManager.setViewportView(tbEmployee);

        pnHistory.add(spTableManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 570, 260));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("History");
        pnHistory.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        dynamicPane.add(pnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 610, 430));

        pnUserSession.setBackground(new java.awt.Color(153, 204, 255));
        pnUserSession.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblUsername.setText("Username");
        pnUserSession.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        lblNik.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        lblNik.setText("NIK");
        pnUserSession.add(lblNik, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        dynamicPane.add(pnUserSession, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 100));

        pnEmpReport.setBackground(new java.awt.Color(204, 204, 204));
        pnEmpReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btReport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btReport.setText("Request Overtime");
        btReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnReportEmpOtLayout = new javax.swing.GroupLayout(pnReportEmpOt);
        pnReportEmpOt.setLayout(pnReportEmpOtLayout);
        pnReportEmpOtLayout.setHorizontalGroup(
            pnReportEmpOtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnReportEmpOtLayout.createSequentialGroup()
                .addComponent(btReport, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 78, Short.MAX_VALUE))
        );
        pnReportEmpOtLayout.setVerticalGroup(
            pnReportEmpOtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btReport, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pnEmpReport.add(pnReportEmpOt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 260, 60));

        btOtReport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btOtReport.setText("Overtime Report");
        btOtReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOtReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnOvtReportLayout = new javax.swing.GroupLayout(pnOvtReport);
        pnOvtReport.setLayout(pnOvtReportLayout);
        pnOvtReportLayout.setHorizontalGroup(
            pnOvtReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnOvtReportLayout.createSequentialGroup()
                .addComponent(btOtReport, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 79, Short.MAX_VALUE))
        );
        pnOvtReportLayout.setVerticalGroup(
            pnOvtReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btOtReport, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pnEmpReport.add(pnOvtReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 260, 60));

        dynamicPane.add(pnEmpReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 180, 430));

        pnMenu.setBackground(new java.awt.Color(51, 153, 255));
        pnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setBackground(new java.awt.Color(255, 255, 255));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHomeMousePressed(evt);
            }
        });
        btnHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        btnHome.add(ind_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Home");
        btnHome.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        pnMenu.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 50));

        btnHistory.setBackground(new java.awt.Color(255, 255, 255));
        btnHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHistoryMousePressed(evt);
            }
        });
        btnHistory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        btnHistory.add(ind_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("History");
        btnHistory.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        pnMenu.add(btnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 130, 50));

        btnAbout.setBackground(new java.awt.Color(255, 255, 255));
        btnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnAboutMousePressed(evt);
            }
        });
        btnAbout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        btnAbout.add(ind_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("About");
        btnAbout.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        pnMenu.add(btnAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, 50));

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnLogoutMousePressed(evt);
            }
        });
        btnLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        btnLogout.add(ind_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Logout");
        btnLogout.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, -1));

        pnMenu.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 130, 50));

        pnHias1.setBackground(new java.awt.Color(51, 153, 255));
        pnHias1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnHias2.setBackground(new java.awt.Color(255, 255, 255));
        pnHias2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnHias3.setBackground(new java.awt.Color(51, 153, 255));
        pnHias3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnHias1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnHias3, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnHias2, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dynamicPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnHias1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnHias3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnHias2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(dynamicPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReportActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        OvertimeReportView op = new OvertimeReportView();
        this.getParent().add(op);
        op.setVisible(true);
    }//GEN-LAST:event_btReportActionPerformed

    private void btOtReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOtReportActionPerformed
        // TODO add your handling code here:
        param.put("id", id);
        try {
            c = factory.
                    getSessionFactoryOptions().getServiceRegistry().
                    getService(ConnectionProvider.class).getConnection();
        } catch (SQLException ex) {
            Logger.getLogger(ManagerMainView.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            String fileName = "./src/report/report1.jrxml";
            String filetoFill = "./src/report/report1.jasper";
            JasperCompileManager.compileReport(fileName);
            JasPri = JasperFillManager.fillReport(filetoFill, param, c);
            JasperViewer.viewReport(JasPri, false);

        } catch (JRException ex) {
            System.out.println(ex.toString());
        }
    }//GEN-LAST:event_btOtReportActionPerformed

    private void tbEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEmployeeMouseClicked
        // TODO add your handling code here:
        if (tbEmployee.getSelectedColumnCount() == 1) {
            int row = tbEmployee.getSelectedRow();
            Sessions.setIdtab(tbEmployee.getValueAt(row, 1).toString());
            this.setVisible(false);
            OvertimeReportView op = new OvertimeReportView();
            this.getParent().add(op);
            op.setVisible(true);
        }
    }//GEN-LAST:event_tbEmployeeMouseClicked

    private void btnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMousePressed
        // TODO add your handling code here:
        setColor(btnHome);
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btnHistory, btnAbout, btnLogout}, new JPanel[]{ind_2, ind_3, ind_4});
//         pnHome.setVisible(true);
//        pnUser.setVisible(false);
        pnHistory.setVisible(true);
//        pnRequest.setVisible(false);
    }//GEN-LAST:event_btnHomeMousePressed

    private void btnHistoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHistoryMousePressed
        // TODO add your handling code here:
        setColor(btnHistory);
        ind_2.setOpaque(true);
        resetColor(new JPanel[]{btnHome, btnAbout, btnLogout}, new JPanel[]{ind_1, ind_3, ind_4});
//         pnHome.setVisible(true);
//        pnUser.setVisible(false);
        pnHistory.setVisible(true);
//        pnRequest.setVisible(false);
    }//GEN-LAST:event_btnHistoryMousePressed

    private void btnAboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAboutMousePressed
        // TODO add your handling code here:
        setColor(btnAbout);
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btnHistory, btnHistory, btnLogout}, new JPanel[]{ind_2, ind_1, ind_4});
//         pnHome.setVisible(true);
//        pnUser.setVisible(false);
        pnHistory.setVisible(true);
//        pnRequest.setVisible(false);
    }//GEN-LAST:event_btnAboutMousePressed

    private void btnLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMousePressed
        // TODO add your handling code here:
        setColor(btnLogout);
        ind_4.setOpaque(true);
        resetColor(new JPanel[]{btnHistory, btnAbout, btnHome}, new JPanel[]{ind_2, ind_3, ind_1});
//         pnHome.setVisible(true);
//        pnUser.setVisible(false);
        pnHistory.setVisible(true);
//        pnRequest.setVisible(false);
    }//GEN-LAST:event_btnLogoutMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOtReport;
    private javax.swing.JButton btReport;
    private javax.swing.JPanel btnAbout;
    private javax.swing.JPanel btnHistory;
    private javax.swing.JPanel btnHome;
    private javax.swing.JPanel btnLogout;
    private javax.swing.JLayeredPane dynamicPane;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblNik;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnEmpReport;
    private javax.swing.JPanel pnHias1;
    private javax.swing.JPanel pnHias2;
    private javax.swing.JPanel pnHias3;
    private javax.swing.JPanel pnHistory;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnOvtReport;
    private javax.swing.JPanel pnReportEmpOt;
    private javax.swing.JPanel pnUserSession;
    private javax.swing.JScrollPane spTableManager;
    private javax.swing.JTable tbEmployee;
    // End of variables declaration//GEN-END:variables
}
